### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by lucassz**
Initial Terraform code implementing steps 1 and 2 of OpenSourcePolicyCenter/PolicyBrain#913, minus the Heroku part. Currently has no dependencies other than two ECR repositories for Celery and Flask with a functional image pushed to them, and can set up a working backend.

@hdoupe

### CODE REVIEW

**Comment by hdoupe** [comment]
@lucassz this looks pretty neat. Can we sit down in the next couple days and get me set up to deploy with these scripts?  I think it'll help me be a bit more familiar and comfortable with these deployment methods if I can get my hands dirty, do some deploys, run some tests, etc.

**Comment by hdoupe** [comment]
@lucassz at some point, can you add something like a `README.md` document explaining:
- why terraform?
- system architecture
  - redis
  - flask
  - celery
  - ...
  - relations between the services
- deployment instructions
- tear down instructions

This can go in a follow up PR, too. You can work on this in parallel with projects that you pick up after this PR is merged. I don't want you to be bogged down with this all summer.

**Comment by lucassz** [comment]
@hdoupe `README.md` has been added. Please let me know if any other information would be helpful within it.

**Comment by hdoupe** [comment]
@lucassz The test app is running on #1 right now. Thanks for revamping our infrastructure and deployment process. From a devops perspective, this improves the webapp many times over. Futher, by decoupling Redis, Flask, and the Celery, data from several tasks could be shared which reduced complexity significantly in the webapp relating to the aggregation of outputs and to distributing, querying and collecting jobs.

**Pull request merged**
